apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-threads-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-threads-test
  template:
    metadata:
      labels:
        app: java-threads-test
    spec:
      containers:
        - name: myap-container
          image: java-threads-test:latest
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
